### PR TITLE
Added overlay for the root of the install directory

### PR DESCRIPTION
**Pull request by mattixtech**
In my opinion its easier to have one overlay copy to the root of OPENNMS_HOME so that no one needs to update this script any time they need to overlay files in a different directory (I'm updating this because I needed to overlay deploy/).

### CODE REVIEW

**Comment by j-white** [comment]
Can we just add a new `OPENNMS_OVERLAY` that overlays over $OPENNMS_HOME instead of removing altering the existing ones? This way we don't break any existing installs.

I'd have the generic overlay run first, followed by the others for the more specific folders.

**Comment by mattixtech** [comment]
> Can we just add a new `OPENNMS_OVERLAY` that overlays over $OPENNMS_HOME instead of removing altering the existing ones? This way we don't break any existing installs.
> 
> I'd have the generic overlay run first, followed by the others for the more specific folders.

Sure, will do that.

**Comment by mattixtech** [comment]
Updated the original commit to preserve the specific overlays for etc and jetty. Won't break any existing overlay config now.

**Comment by indigo423** [comment]
Is there anything we have to tell people in the README?

**Comment by mattixtech** [comment]
> Is there anything we have to tell people in the README? Otherwise 👍 from me.

Good point, I will update the README to point out the OPENNMS_HOME overlay directory.

**Comment by mattixtech** [comment]
Lets hold off on merging this as I'm not sure I need this change anymore as I might be able to get away with just overlaying files in etc/ which is already supported by the script.

**Comment by mattixtech** [comment]
I ended up not needing to overlay any files outside of etc so I've removed that change.

Note that this PR depends on https://github.com/OpenNMS/opennms/pull/2178/ so lets wait on merging this.

Thanks!

**Comment by mattixtech** [comment]
We've come full circle back to just updating the overlay for the root of the install and no longer updating karaf features...

The PR is no longer dependent on anything so we can merge as soon as its reviewed. Thanks.

**Pull request merged**
