### PR TITLE
resolve #32 - add environment variables for SMTP configuration

### LINKED ISSUE #32: notifd cann't send notification e-mails
If I configure Opennms Horizon to send notification e-mails, mailer fails, because postfix is missing.

I've installed postfix:
`yum install postfix`
I tried to start service, but it is not possible from _/etc/init.d_ directory. So I tried to start it with command _postfix start_. It failed, because of error:
`postfix: fatal: parameter inet_interfaces: no local interface found for ::1`
I've changed one line in /etc/postfix/main.cf:
`sed -i 's/protocols = all/protocols = ipv4/g' /etc/postfix/main.cf`
Then _postfix start_ started postfix successfully. But it will not be automatic, because /etc/init.d/postfix is missing.

Could be e-mail support added and configurable?

```
2018-08-28 05:33:47,529 ERROR [NotificationTask-101] o.o.j.JavaMailer: Java Mailer messaging exception: javax.mail.MessagingException: Could not connect to SMTP host: 127.0.0.1, port: 25 (java.net.ConnectException: Connection refused (Connection refused))
javax.mail.MessagingException: Could not connect to SMTP host: 127.0.0.1, port: 25 (java.net.ConnectException: Connection refused (Connection refused))
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972) ~[mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642) ~[mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:251) ~[geronimo-javamail_1.4_spec-1.7.1.jar:1.7.1]
        at org.opennms.javamail.JavaMailer.sendMessage(JavaMailer.java:448) [opennms-javamail-api-23.0.0-SNAPSHOT.jar:?]
        at org.opennms.javamail.JavaMailer.mailSend(JavaMailer.java:250) [opennms-javamail-api-23.0.0-SNAPSHOT.jar:?]
        at org.opennms.netmgt.notifd.JavaMailNotificationStrategy.send(JavaMailNotificationStrategy.java:71) [opennms-services-23.0.0-SNAPSHOT.jar:?]
        at org.opennms.netmgt.notifd.ClassExecutor.execute(ClassExecutor.java:69) [opennms-services-23.0.0-SNAPSHOT.jar:?]
        at org.opennms.netmgt.notifd.NotificationTask.run(NotificationTask.java:274) [opennms-services-23.0.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_181]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_181]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_181]
        at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_181]
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:319) ~[mail-1.4.5.jar:1.4.5]
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:233) ~[mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1938) ~[mail-1.4.5.jar:1.4.5]
        ... 10 more

org.opennms.javamail.JavaMailerException: Java Mailer messaging exception: javax.mail.MessagingException: Could not connect to SMTP host: 127.0.0.1, port: 25 (java.net.ConnectException: Connection refused (Connection refused))
        at org.opennms.javamail.JavaMailer.sendMessage(JavaMailer.java:458) ~[opennms-javamail-api-23.0.0-SNAPSHOT.jar:?]
        at org.opennms.javamail.JavaMailer.mailSend(JavaMailer.java:250) ~[opennms-javamail-api-23.0.0-SNAPSHOT.jar:?]
        at org.opennms.netmgt.notifd.JavaMailNotificationStrategy.send(JavaMailNotificationStrategy.java:71) [opennms-services-23.0.0-SNAPSHOT.jar:?]
        at org.opennms.netmgt.notifd.ClassExecutor.execute(ClassExecutor.java:69) [opennms-services-23.0.0-SNAPSHOT.jar:?]
        at org.opennms.netmgt.notifd.NotificationTask.run(NotificationTask.java:274) [opennms-services-23.0.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: 127.0.0.1, port: 25 (java.net.ConnectException: Connection refused (Connection refused))
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972) ~[mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642) ~[mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:251) ~[geronimo-javamail_1.4_spec-1.7.1.jar:1.7.1]
        at org.opennms.javamail.JavaMailer.sendMessage(JavaMailer.java:448) ~[opennms-javamail-api-23.0.0-SNAPSHOT.jar:?]
        ... 7 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_181]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_181]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_181]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_181]
        at java.net.Socket.connect(Socket.java:538) ~[?:1.8.0_181]
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:319) ~[mail-1.4.5.jar:1.4.5]
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:233) ~[mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1938) ~[mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642) ~[mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:251) ~[geronimo-javamail_1.4_spec-1.7.1.jar:1.7.1]
        at org.opennms.javamail.JavaMailer.sendMessage(JavaMailer.java:448) ~[opennms-javamail-api-23.0.0-SNAPSHOT.jar:?]
        ... 7 more

```

### PR DESCRIPTION
**Pull request by honyczek**
Possible solution to issue #32

### CODE REVIEW

**Comment by indigo423** [comment]
To be honest, we have to decide where do we draw the line between configuration through environment variables and configuration files. We tried to use template files just for the bare minimum things to get the application started (Postgres/Newts).

There are hundreds of configuration options in OpenNMS which need to be edited through config files and you have to maintain them anyways in an accessible directory. To address this problem we have introduced the etc-overlay directory as a convention. All files you drop in here, are injected on startup in the container config. You can just drop a javamail-configuration.properties in etc-overlay and you are done. Adding more template files increases the dependency of configuration file formats and I would vote for having less configuration file dependencies as possible.

Thank you for your contribution. Would be happy to get your feedback about it.

**Comment by honyczek** [comment]
@indigo423 Sure I understand. I don't know if it is so important for others, but I prefer sending e-mails if there is any notification. For me it is a necessary feature. Maybe others have OpenNMS dashboard opened all day. I go to UI only when I need some specific information. In other cases I believe no e-mail = no outage. Actually at first I have used etc-overlay for changing javamail configuration. Then I prepared this solution if you feel it as necessary as me.

**Comment by indigo423** [comment]
@honyczek Absolutely no question about your E-Mail notification use case, this makes totally sense. What I mean is more the way to configure it. Just to explain what I mean. Your change introduces 2 new environment variables `OPENNMS_MAIL_FROM` and `OPENNMS_MAIL_SMTPHOST`. It solves your use case but there are 13 other configuration options which can't be set through the environment. As soon somebody needs to change any of the 13 other configuration options - which is extrem likely - he needs to follow the etc-overlay configuration pattern. You draw the line for environment configuration for the two you needed in fits your use case and kept the 13 others out.

I would like to come to a decision to a) make them all configurable through the environment or b) keep the etc-overlay pattern.

In my opinion, when we decide to make a) we have to maintain a dependency of the template for the javamail-configuration.properties. Cause as soon the OpenNMS changes this format or adds new options we have to change the template in this repository here as well and force people to update the docker image and adjust the environment configuration variables accordingly. In my opinion it would be much easier if each user just changes is javamail-properties file and restart the container and is done.

What do you think?

**Comment by honyczek** [comment]
You're right.

**Pull request closed without merging**
